### ISSUE TITLE
Crashes on pre-Lollipop

### ISSUE THREAD

**Issue by IgorGanapolsky** [lgvalle/Material-Animations#7]
Hi,
I am trying to run your project on a JellyBean emulator, and it crashes with 
> java.lang.NoClassDefFoundError: android.transition.Explode

My question is, is it possible to make this stuff run on pre-Lollipop devices?

**Comment by evasyuk** [comment]
explode animation wouldn't work on Android lower 4.3 or 4.4(don't remember precise version). JellyBean is 4.1\4.2

**Comment by lgvalle** [comment]
As @evasyuk said, `Explode`needs API 21

https://developer.android.com/reference/android/transition/Explode.html

So I'm afraid answer is no. You can't run this examples on pre-lollipop devices
